### ISSUE TITLE
Module '"react-native-stock-star-rating"' has no exported member 'Rating'

### ISSUE THREAD

**Issue by anangkf** [mmusaib/react-native-stock-star-rating#1]
hi @mmusaib, 
i faced an error when importing Rating component from react-native-stock-star-rating.
when i hover over the import statement it just containing RatingProps. any advice?
![image](https://github.com/mmusaib/react-native-stock-star-rating/assets/78357037/7a64980f-ea12-427d-9419-787832cc7de8)

**Comment by mmusaib** [comment]
I think it is the issue with your IDE. It is not the issue with the package. You write the full import statement manually like below,

```js
import { Rating } from 'react-native-stock-star-rating';
```

**Comment by anangkf** [comment]
writing it manually doesnt solve the issue, anyway i decided to use another package :)

**Comment by mmusaib** [comment]
Wait. Let me have  a look at it.. Are you using expo or react-native ?

**Comment by mmusaib** [comment]
I doesn't show the autocomplete in the IDE but it is working...

You can check this expo snack for reference https://snack.expo.dev/@mmusaib/react-native-stock-star-rating

**Comment by anangkf** [comment]
Ohh sorry I forget to mention that I am working on expo + typescript project.

I have no idea about the issue. even though it raises an typescript error, it gives output as expected.
I mean nothing happened at the runtime, rating component rendered successfully

**Comment by mmusaib** [comment]
That is what I was saying. It might be the typescript warning that you might be facing. Anyways, happy to help

**Comment by anangkf** [comment]
Aaahh, thats it. Thank you @mmusaib!
